accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm, PWSResetForm, PwdResetConfirmForm, PassChangeForm

app_name = 'accounts'

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(
             template_name='registration/login.html',
             authentication_form=UserLoginForm),
         name='login'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change_form.html', form_class=PassChangeForm),
         name='password_change'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html', form_class=PWSResetForm),
         name='password_reset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html', form_class=PwdResetConfirmForm),
         name="pwdresetconfirm"),

    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/delete/', views.delete_profile, name='delete_profile'),

    path('fav/<int:pk>/', views.add_to_favorites, name='add_to_favorites'),
    path('profile/favorite_list/', views.favorite_list, name='favorite_list'),
    path('like/', views.like, name='like'),

    path('thumbs/', views.thumbs, name='thumbs'),

    path('register/', views.accounts_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
]

blogapp/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from blogapp import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('createpost/', login_required(views.CreatePostView.as_view()), name='createpost'),
    path('search/', views.post_search, name='search'),
    path('addcomment/', views.add_comment, name='addcomment'),
    path('<int:pk>/', views.single_post, name='single_post'),
    path('category/<category>/', login_required(views.CategoryListView.as_view()), name='category'),

]

myblog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    # path('secret/', include(admin.site.urls)),  # this is the new admin path
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blog')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('account/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

templates/partials/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %} Welcome to blog {% endblock %}</title>
    <style>
        .small {
            font-size: 0.875rem;
            color: #4b4b4b;
        }
    </style>
</head>
<body>

{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/partials/footer.html
{% load static %}
{#<div class="container bg-dark">#}
    <footer class="pt-4 pt-md-5 border-top bg-dark">
        <div class="row mx-3">
            <div class="col-6 col-md">
                <h5 class="features">Features</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Cool stuff</a></li>
                    <li><a class="text-muted" href="#">Random feature</a></li>
                    <li><a class="text-muted" href="#">Team feature</a></li>
                    <li><a class="text-muted" href="#">Stuff for developers</a></li>
                    <li><a class="text-muted" href="#">Another one</a></li>
                    <li><a class="text-muted" href="#">Last time</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5 class="features">Resources</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Resource</a></li>
                    <li><a class="text-muted" href="#">Resource name</a></li>
                    <li><a class="text-muted" href="#">Another resource</a></li>
                    <li><a class="text-muted" href="#">Final resource</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5 class="features">About</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Team</a></li>
                    <li><a class="text-muted" href="#">Locations</a></li>
                    <li><a class="text-muted" href="#">Privacy</a></li>
                    <li><a class="text-muted" href="#">Terms</a></li>
                </ul>
            </div>
            <div class="col-12 col-md">
                <img class="mb-2" src="{% static 'small.jpeg' %}" alt="" width="50"
                     height="50">
                <small class="d-block mb-3 text-muted">&copy; 2017-2020</small>
            </div>
        </div>
    </footer>
</div>

templates/partials/navbar.html
{% load static %}
<style>
    .avatar {
        height: 50px;
        width: 50px;
        background-color: #000;
        border-radius: 50%;
        display: inline-block;
    }
</style>

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 navbar-dark bg-dark border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a class="text-light" href="{% url 'blog:home' %}">NGU&KG</a></h5>
    {#    <nav class="my-2 my-md-0 mr-md-3">#}
    {#        <a class="p-2 text-light" href="#">Features</a>#}
    {#        <a class="p-2 text-light" href="#">Enterprise</a>#}
    {#        <a class="p-2 text-light" href="#">Support</a>#}
    {#    </nav>#}
    {% if request.user.is_authenticated %}
        <img class="avatar" src="
            {% for data in avatar %}
                {% if data.avatar.url %}
                    {{ data.avatar.url }}
                {% else %}
                    {% static 'avatar.jpeg' %}
                {% endif %}
            {% endfor %} ">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Dashboard</a>
                    <a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">Edit details</a>
                    <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                    <div class="dropdown-divider"></div>
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    {% endif %}
                </div>
            </li>
        </ul>
    {% else %}
        <nav>
            {#            <a class="p-2 text-dark" href="{% url 'accounts:register' %}">Register</a>#}
            <a class="p-2 text-light" href="{% url 'login' %}">Login</a>
        </nav>
    {% endif %}
</div>