accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm, PWSResetForm, PwdResetConfirmForm, PassChangeForm

app_name = 'accounts'

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(
             template_name='registration/login.html',
             authentication_form=UserLoginForm),
         name='login'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change_form.html', form_class=PassChangeForm),
         name='password_change'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html', form_class=PWSResetForm),
         name='password_reset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html', form_class=PwdResetConfirmForm),
         name="pwdresetconfirm"),

    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/delete/', views.delete_profile, name='delete_profile'),

    path('fav/<int:pk>/', views.add_to_favorites, name='add_to_favorites'),
    path('profile/favorite_list/', views.favorite_list, name='favorite_list'),
    path('like/', views.like, name='like'),

    path('thumbs/', views.thumbs, name='thumbs'),

    path('register/', views.accounts_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
]

blogapp/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from blogapp import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('createpost/', login_required(views.CreatePostView.as_view()), name='createpost'),
    path('search/', views.post_search, name='search'),
    path('addcomment/', views.add_comment, name='addcomment'),
    path('<int:pk>/', views.single_post, name='single_post'),
    path('category/<category>/', login_required(views.CategoryListView.as_view()), name='category'),

]

myblog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    # path('secret/', include(admin.site.urls)),  # this is the new admin path
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blog')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('account/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, SetPasswordForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from accounts.models import Profile


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Username'}
    ))
    password = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': 'password',
               'placeholder': 'Your password', 'id': 'login-pwd'}
    ))


class UserRegisterForm(forms.ModelForm):
    username = forms.CharField(
        label='Enter username', min_length=4, max_length=50, help_text='Required')
    email = forms.EmailField(max_length=100, help_text='Required', error_messages={
        'required': 'Sorry, you will need an email'})
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'form-control mb-3', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update({
            'class': 'form-control mb-3', 'placeholder': 'email', 'name': 'email'})
        self.fields['password'].widget.attrs.update({
            'class': 'form-control mb-3', 'placeholder': 'Password'})
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control mb-3', 'placeholder': 'Confirmation password'})

    # This is for checking the user if exists in the db
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise ValueError("The username already exists!")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.exists():
            raise ValidationError("The email already exists!")
        return email

    # make the password1 and password2 are equal
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise ValidationError('Passwords do not match.')
        return cd['password2']


class PWSResetForm(PasswordResetForm):
    email = forms.EmailField(max_length=100, help_text='Required', widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Email', 'id': 'form-email'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        test = User.objects.filter(email=email)
        if not test:
            raise forms.ValidationError("The email doesn't exists in our database try to register!")
        return email


class PwdResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-new-pass2'}))


class UserEditForm(forms.ModelForm):
    first_name = forms.CharField(
        label='Firstname', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Firstname', 'id': 'form-firstname'}))

    last_name = forms.CharField(
        label='Lastname', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Lastname', 'id': 'form-lastname'}))

    email = forms.EmailField(
        max_length=200, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Old Password', 'id': 'form-email'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    # def clean_email(self):
    #     email = self.cleaned_data['email']
    #     if User.objects.filter(email=email).exists():
    #         raise forms.ValidationError(
    #             'Please use another Email, that is already taken')
    #     return email

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['last_name'].required = False
        self.fields['email'].required = False


class PassChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='Old Password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Old Password', 'id': 'form-oldpass'}))
    new_password1 = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-new-pass2'}))


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'avatar']
        widgets = {
            'bio': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'})
        }

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.db.models import F, Q
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from blogapp.models import Post, Vote
from .models import Profile
from .tokens import account_activation_token
from .forms import UserRegisterForm, UserEditForm, UserProfileForm


# def login(request):
#     return render(request, 'registration/login.html')

@login_required
def avatar_get(request):
    user = User.objects.get(username=request.user)
    avatar = Profile.objects.filter(user=user)
    context = {
        'user': user,
        'avatar': avatar
    }
    return context


@login_required
def profile(request):
    return render(request, 'accounts/profile.html', {'section': 'profile'})


def accounts_register(request):
    # if they registered do that
    if request.method == 'POST':
        register_form = UserRegisterForm(request.POST)
        if register_form.is_valid():  # check the data if it is valid
            user = register_form.save(commit=False)
            user.email = register_form.cleaned_data['email']
            user.set_password(register_form.cleaned_data['password'])
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            subject = 'Activate your account'
            context = {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user)
            }
            message = render_to_string('registration/account_activation_email.html', context)
            user.email_user(subject=subject, message=message)
            return HttpResponse('You successfully registered, and the activation sent')

    # if the user want to register show the form
    else:
        register_form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': register_form})


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('login')
    else:
        return render(request, 'registration/activation_invalid.html')


@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)

        profile_form = UserProfileForm(
            request.POST, request.FILES,
            instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = UserProfileForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form
    }

    return render(request, 'accounts/update.html', context)


@login_required
def delete_profile(request):
    if request.method == 'POST':
        user = User.objects.get(username=request.user)
        # disable the account from db
        user.is_active = False
        user.save()
        return redirect('accounts:login')
    else:
        return render(request, 'accounts/delete_account.html')


@login_required
def add_to_favorites(request, pk):
    post = get_object_or_404(Post, id=pk)
    # user = User.objects.get(username=request.user)
    if post.favorites.filter(id=request.user.id).exists():
        post.favorites.remove(request.user)
    else:
        post.favorites.add(request.user)

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def favorite_list(request):
    new = Post.new_manager.filter(favorites=request.user)
    return render(request, 'accounts/favorites.html', {'new': new})


@login_required
def like(request):
    if request.POST.get('action') == 'post':
        result = ''
        id = int(request.POST.get('postid'))
        post = get_object_or_404(Post, id=id)
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
            post.like_count -= 1
            result = post.like_count
            post.save()
        else:
            post.likes.add(request.user)
            post.like_count += 1
            result = post.like_count
            post.save()

        return JsonResponse({'result': result, })


def thumbs(request):
    if request.POST.get('action') == 'thumbs':

        id = int(request.POST.get('postid'))
        button = request.POST.get('button')
        update = Post.objects.get(id=id)

        if update.thumbs.filter(id=request.user.id).exists():

            # Get the users current vote (True/False)
            q = Vote.objects.get(
                Q(post_id=id) & Q(user_id=request.user.id))
            evote = q.vote

            if evote == True:

                # Now we need action based upon what button pressed

                if button == 'thumbsup':
                    update.thumbsup = F('thumbsup') - 1
                    update.thumbs.remove(request.user)
                    update.save()
                    update.refresh_from_db()
                    up = update.thumbsup
                    down = update.thumbsdown
                    q.delete()

                    return JsonResponse({'up': up, 'down': down, 'remove': 'none'})

                if button == 'thumbsdown':
                    # Change vote in Post
                    update.thumbsup = F('thumbsup') - 1
                    update.thumbsdown = F('thumbsdown') + 1
                    update.save()

                    # Update Vote

                    q.vote = False
                    q.save(update_fields=['vote'])

                    # Return updated votes
                    update.refresh_from_db()
                    up = update.thumbsup
                    down = update.thumbsdown

                    return JsonResponse({'up': up, 'down': down})

            pass

            if evote == False:

                if button == 'thumbsup':
                    # Change vote in Post
                    update.thumbsup = F('thumbsup') + 1
                    update.thumbsdown = F('thumbsdown') - 1
                    update.save()

                    # Update Vote

                    q.vote = True
                    q.save(update_fields=['vote'])

                    # Return updated votes
                    update.refresh_from_db()
                    up = update.thumbsup
                    down = update.thumbsdown

                    return JsonResponse({'up': up, 'down': down})

                if button == 'thumbsdown':
                    update.thumbsdown = F('thumbsdown') - 1
                    update.thumbs.remove(request.user)
                    update.save()
                    update.refresh_from_db()
                    up = update.thumbsup
                    down = update.thumbsdown
                    q.delete()

                    return JsonResponse({'up': up, 'down': down, 'remove': 'none'})

        else:  # New selection

            if button == 'thumbsup':
                update.thumbsup = F('thumbsup') + 1
                update.thumbs.add(request.user)
                update.save()
                # Add new vote
                new = Vote(post_id=id, user_id=request.user.id, vote=True)
                new.save()
            else:
                # Add vote down
                update.thumbsdown = F('thumbsdown') + 1
                update.thumbs.add(request.user)
                update.save()
                # Add new vote
                new = Vote(post_id=id, user_id=request.user.id, vote=False)
                new.save()

            # Return updated votes
            update.refresh_from_db()
            up = update.thumbsup
            down = update.thumbsdown

            return JsonResponse({'up': up, 'down': down})

    pass

templates/accounts/delete_account.html
{% extends 'partials/base.html' %}

{% block title %}Profile{% endblock %}
{% block content %}

    <div class="container-fluid my-5">
        <section class="px-md-5 mx-md-5 text-center text-lg-left dark-grey-text">
            <div class="row d-flex justify-content-center">
                <div class="col-md-6">
                    <form class="form-reset p-4 rounded update-form" action="{% url "accounts:delete_profile" %}"
                          method="post">
                        {% csrf_token %}
                        <p class=" h5 mb-2 pt-4 font-weight-bold">Delete Account</p>
                        <p>Are you sure you want to delete your account?
                            *Important - your account data will remain available for 20 days</p>
                        <button type="submit" role="button"
                                class="btn btn-danger btn-block py-2 mb-4 mt-5 font-weight-bold">Delete
                        </button>
                    </form>
                    <p class="small text-center pt-4">
                        <a href="{% url "accounts:profile" %}">Back to Dashboard</a>
                    </p>
                    <p class="small text-center">
                        <a href="{% url "accounts:register" %}">Help Center?</a>
                    </p>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

templates/accounts/favorites.html
{% extends 'blogapp/base.html' %}
{% block title %}Profile{% endblock %}
{% block content %}
    <div class="container">
        <section class="jumbotron text-center bg-white">
            <div class="container">
                <h1>User favorites</h1>
                <p class="lead text-muted">You can remove any post from your list at anytime you want!!</p>
            </div>
        </section>
        <div>
            <div class="row">

                {% for post in new %}
                    <div class="col-md-4">
                        <a href="{% url 'blog:single_post' post.pk %}" class="text-dark">
                            <div class="card mb-4 box-shadow">
                                <img class="card-img-top" style="width: 350px; height: 250px" src="{{ post.image.url }}"
                                     alt="{{ post.title }}">
                                <div class="card-body">
                                    <h2 style="font-size: 18px; font-weight: bold;">
                                        {{ post.title|truncatechars:10|capfirst }}
                                    </h2>
                                    <p class="card-text">{{ post.excerpt|truncatechars:10 }}</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <small class="text-muted">{{ post.publish|date }}</small>
                                        <div id="favorite-section">
                                        <a class="btn btn-outline-danger"
                                           href="{% url 'accounts:add_to_favorites' post.pk %}">
                                            Remove from favorites
                                        </a>
                                    </div>
                                    </div>

                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% include "partials/footer.html" %}
{% endblock %}

templates/accounts/profile.html
{% extends "partials/base.html" %}
{% load static %}

{% block title %}Profile{% endblock %}
{% block content %}
    {% include "partials/navbar.html" %}
    <div class="container">
        <div class="col-sm">
            <div class="row ">
                <img src="{{ user.profile.avatar }}">
                <h3 class="mx-5">{{ user.username }}</h3>
            </div>
        </div>
        <section class="jumbotron text-center bg-white">
            <div class="container">
                <h1>User Dashboard</h1>
                <p class="lead text-muted">{{ user.profile.bio }}<p>
                <a href="{% url 'logout' %}" class="btn btn-primary my-2">Logout</a>
            </p>
            </div>
        </section>

    </div>
    {% include "partials/footer.html" %}
{% endblock %}

templates/accounts/update.html
{% extends "partials/base.html" %}

{% block title %}Edit your account{% endblock %}
{% block content %}
    {% include "partials/navbar.html" %}

    <div class="container-fluid my-5">
        <section class="px-md-5 mx-md-5 text-center text-lg-left dark-grey-text">
            <div class="row d-flex justify-content-center">
                <div class="col-md-6">

                    <form class="form-reset p-4 rounded update-form" method="post" enctype="multipart/form-data">

                        {% if user_form.is_valid and profile_form.is_valid %}
                            <div class="alert alert-primary" role="alert">
                                Details successfully updated!
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            <p class="small text-center pt-0">
                                <a href="{% url "accounts:profile" %}">Back to Dashboard</a>
                            </p>
                        {% else %}
                            <p class=" h4 mb-4 font-weight-bold">Change your details</p>
                            <p>You can edit your account using the following form:</p>
                        {% endif %}

                        {% if form.errors %}
                            <div class="alert alert-primary" role="alert">
                                Error: Please try again!
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                        {% endif %}

                        {% if profile_form.errors %}
                            <div class="alert alert-primary" role="alert">
                                The image size should be 200x200
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                        {% endif %}

                        {% csrf_token %}
                        <label class="small font-weight-bold">{{ user_form.first_name.label }}</label>
                        {{ user_form.first_name }}
                        <label class="small font-weight-bold">{{ user_form.last_name.label }}</label>
                        {{ user_form.last_name }}
                        <label class="small font-weight-bold">{{ user_form.email.label }}</label>
                        {{ user_form.email }}

                        <label class="small font-weight-bold">{{ profile_form.bio.label }}</label>
                        {{ profile_form.bio }}

                        <div class="form-group pt-5">
                            <label class="small font-weight-bold">{{ profile_form.avatar.label }}</label>
                            {{ profile_form.avatar }}
                        </div>

                        <button class="btn btn-primary btn-block py-2 mb-4 mt-5 font-weight-bold" type="submit"
                                value="Save changes">Save Changes
                        </button>
                        <hr class="mb-3">
                        <p class=" h5 mb-2 pt-4 font-weight-bold">Delete Account</p>
                        <p class="small">
                            If you would like to delete your account press the button below:</p>

                        <a href="{% url "accounts:delete_profile" %}"
                           class="btn btn-danger btn-block py-2 mb-4 mt-5 font-weight-bold"
                           role="button"
                           aria-pressed="true">Delete your Account</a>
                    </form>

                </div>
            </div>
        </section>
    </div>
    {% include "partials/footer.html" %}
{% endblock %}