accounts/urls.py
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm, PWSResetForm, PwdResetConfirmForm, PassChangeForm

app_name = 'accounts'

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(
             template_name='registration/login.html',
             authentication_form=UserLoginForm),
         name='login'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change_form.html', form_class=PassChangeForm),
         name='password_change'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset_form.html', form_class=PWSResetForm),
         name='password_reset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html', form_class=PwdResetConfirmForm),
         name="pwdresetconfirm"),

    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/delete/', views.delete_profile, name='delete_profile'),

    path('fav/<int:pk>/', views.add_to_favorites, name='add_to_favorites'),
    path('profile/favorite_list/', views.favorite_list, name='favorite_list'),
    path('like/', views.like, name='like'),

    path('thumbs/', views.thumbs, name='thumbs'),

    path('register/', views.accounts_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate'),
]

blogapp/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from blogapp import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('createpost/', login_required(views.CreatePostView.as_view()), name='createpost'),
    path('search/', views.post_search, name='search'),
    path('addcomment/', views.add_comment, name='addcomment'),
    path('<int:pk>/', views.single_post, name='single_post'),
    path('category/<category>/', login_required(views.CategoryListView.as_view()), name='category'),

]

myblog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    # path('secret/', include(admin.site.urls)),  # this is the new admin path
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blog')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('account/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from mptt.models import MPTTModel, TreeForeignKey
from django.db import models


# User = settings.AUTH_USER_MODEL


def user_directory_path(instance, filename):
    # return 'posts/%Y/%m/%d/'.format(instance.id, filename)
    return 'posts/{0}/{1}'.format(instance.id, filename)


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Post(models.Model):
    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status='published')

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=200)
    # models.PROTECT will allow us to keep our post in our database
    category = models.ForeignKey(Category, on_delete=models.PROTECT, default=2)
    excerpt = models.TextField()
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts', null=True, blank=True)
    content = models.TextField()
    status = models.CharField(max_length=10, choices=options, default='draft')
    favorites = models.ManyToManyField(User, related_name='favorite', default=None, blank=True)

    likes = models.ManyToManyField(User, related_name='like', default=None, blank=True)
    like_count = models.BigIntegerField(default='0')

    thumbs = models.ManyToManyField(User, related_name='thumbs', default=None, blank=True)
    thumbsup = models.IntegerField(default='0')
    thumbsdown = models.IntegerField(default='0')

    image = models.ImageField(upload_to=user_directory_path, default='posts/trees.jpeg')

    # instead of using everytime the order we need to make it by default
    objects = models.Manager()  # default manager
    new_manager = NewManager()  # custom manager

    class Meta:
        # add "-" showing the last one added (by newer post)
        ordering = ['-publish', ]

    def __str__(self):
        return self.title

    # def save(self, *args, **kwargs):
    #     if self.slug is None:
    #         self.slug = slugify(self.title)
    #     else:
    #         self.slug = slugify(self.slug)
    #
    #     super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:home')

    # we can use this instead of signals in this case

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title)
    #     super(Post, self).save(*args, **kwargs)


class Comment(MPTTModel):
    author = models.ForeignKey(User, related_name='author', on_delete=models.CASCADE, default=None, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')
    # name = models.CharField(max_length=50)
    # email = models.EmailField()
    content = models.TextField()
    date_commented = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    # we don't need this meta class
    # class Meta:
    #     # add "-" showing the last one added (by newer post)
    #     ordering = ('date_commented',)

    class MPTTMeta:
        order_insertion_by = ['date_commented']

    # def __str__(self):
    #     return f"Comment by {self.name}"


class Vote(models.Model):
    post = models.ForeignKey(Post, related_name='postid',
                             on_delete=models.CASCADE, default=None, blank=True)
    user = models.ForeignKey(User, related_name='userid',
                             on_delete=models.CASCADE, default=None, blank=True)
    vote = models.BooleanField(default=True)

blogapp/forms.py
from django import forms
from mptt.forms import TreeNodeChoiceField

from blogapp.models import Comment, Category, Post


class CommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['parent'].required = False
        self.fields['parent'].label = ''
        self.fields['parent'].widget.attrs.update(
            {'class': 'd-none'}
        )

    class Meta:
        model = Comment
        fields = ('post', 'parent', 'content')
        widgets = {
            'content': forms.Textarea(attrs={"class": "ml-3 mb-3 form-control border-0"
                                                      "comment-add rounded-0",
                                             'rows': 1, 'placeholder': 'Add a public comment'})}

        def save(self, *args, **kwargs):
            Comment.objects.rebuild()
            return super(CommentForm, self).save(*args, **kwargs)


class SearchForm(forms.Form):
    q = forms.CharField()

    # categories = forms.ModelChoiceField(
    #     queryset=Category.objects.all().order_by('name')
    # )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['categories'].required = False
        # self.fields['categories'].label = ''
        # self.fields['categories'].label = 'Category'
        # self.fields['categories'].widget.attrs.update({
        #     'class': 'my-3'})

        self.fields['q'].label = 'Search for'
        self.fields['q'].widget.attrs.update({
            'class': 'form-control menudd'})
        self.fields['q'].widget.attrs.update({
            'data-toggle': 'dropdown'})


choices = Category.objects.all().values_list('name', 'name')

choice_list = []
for item in choices:
    choice_list.append(item)


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'category', 'excerpt', 'content', 'status', 'image')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control',
                                            'placeholder': 'Type your title here'}),
            'excerpt': forms.TextInput(attrs={'class': 'form-control',
                                              'placeholder': 'Type your tag here'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'value': '', 'type': 'hidden',
                                             'id': 'usernameId'}),
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
        }

blogapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, CreateView

from blogapp.forms import CommentForm, SearchForm, PostForm
from blogapp.models import Post, Category, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q


def home(request):
    posts = Post.new_manager.all()
    context = {
        'posts': posts
    }
    return render(request, 'blogapp/home.html', context)


def single_post(request, pk):
    post = get_object_or_404(Post, pk=pk, status='published')

    favorite = bool
    if post.favorites.filter(id=request.user.id).exists():
        favorite = True

    allcomments = post.comments.filter(status=True)

    # page = request.GET.get('page', 1)
    # paginator = Paginator(allcomments, 2)
    # try:
    #     comments = paginator.page(page)
    # except PageNotAnInteger:
    #     comments = paginator.page(1)
    # except EmptyPage:
    #     comments = paginator.page(paginator.num_pages)
    #
    # user_comment = None
    #
    # if request.method == 'POST':
    #     comment_form = CommentForm(request.POST)
    #     if comment_form.is_valid():
    #         user_comment = comment_form.save(commit=False)
    #         user_comment.post = post
    #         user_comment.save()
    #         return HttpResponseRedirect('/' + post.slug)
    # else:
    #     comment_form = CommentForm()

    comment_form = CommentForm()

    context = {
        'comment_form': comment_form,
        'post': post,
        # 'comments': comments,
        # 'user_comment': user_comment,
        'allcomments': allcomments,
        'favorite': favorite,
    }
    return render(request, 'blogapp/single_post.html', context)


def add_comment(request):
    """
    Will capture the Ajax requests, when we create new comment that will going to
    create new ajax request and sent to this view and capture it using the if request.method == post
    """
    if request.method == "POST":

        if request.POST.get('action') == 'delete':
            id = request.POST.get('nodeid')
            c = Comment.objects.get(id=id)
            c.delete()
            return JsonResponse({'remove': id})

        else:
            comment_form = CommentForm(request.POST)

            if comment_form.is_valid():
                user_comment = comment_form.save(commit=False)
                user_comment.author = request.user
                user_comment.save()

                result = comment_form.cleaned_data.get('content')
                user = request.user.username

                return JsonResponse({'result': result, 'user': user})


class CategoryListView(ListView):
    template_name = 'blogapp/category.html'
    context_object_name = 'categorylist'

    def get_queryset(self):
        content = {
            'category': self.kwargs['category'],
            'posts': Post.objects.filter(category__name=self.kwargs['category']
                                         ).filter(status='published')
        }
        return content


def category_list(request):
    categories = Category.objects.exclude(name='default')
    context = {
        'categories': categories,
    }
    return context


# def post_search(request):
#     form = SearchForm()
#     q = ''
#     # c = ''
#     results = []
#     query = Q()
#
#     # this is caption the data that sent from ajax request
#     if request.POST.get('action') == 'post':
#         search_string = str(request.POST.get('ss'))
#
#         if search_string is not None:
#             search_string = Post.objects.filter(title__contains=search_string)[:3]
#             # As we know Javascript and python they can't talk to each others,
#             # so we need to serialize the data the gets return from database
#             data = serializers.serialize('json',
#                                          list(search_string),
#                                          fields=('id', 'title', 'slug'))
#
#             return JsonResponse({'search_string': data})
#
#     if 'q' in request.GET:
#         form = SearchForm(request.GET)
#         if form.is_valid():
#             q = form.cleaned_data['q']
#             # c = form.cleaned_data['categories']
#             #
#             # if c is not None:
#             #     query &= Q(category=c)
#             if q != '':
#                 query &= Q(title__contains=q)
#
#             results = Post.objects.filter(query)
#
#     context = {'form': form, 'q': q, 'results': results}
#     return render(request, 'blogapp/search.html', context)


def post_search(request):
    form = SearchForm()
    q = ''
    results = []
    context = {}

    if 'q' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            q = form.cleaned_data['q']

            # results = Post.objects.filter(title__search=q)

            # results = Post.objects.annotate(search=SearchVector(
            #     'title', 'content'),).filter(search=q)

            # results = Post.objects.annotate(search=SearchVector(
            #         'title', 'content'),).filter(search=SearchQuery(q))

            vector = SearchVector('title', weight='A') + SearchVector('content', weight='B')
            query = SearchQuery('q')

            # results = Post.objects.annotate(
            #     rank=SearchRank(vector, query, cover_density=True)) \
            #     .order_by('-publish')
            results = Post.objects.filter(Q(title__icontains=q) |
                                        Q(content__icontains=q))

        context = {'form': form, 'q': q, 'results': results}
    return render(request, 'blogapp/search.html', context)


class CreatePostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blogapp/add_post.html'

blogapp/templates/blogapp/add_post.html
{% extends 'blogapp/base.html' %}
{% load static %}
{% block title %}Add Post{% endblock %}

{% block content %}
    {% if user.is_authenticated and user.is_superuser %}
        <h1 class="form-group d-flex my-5 mx-3">Add Post . . . !</h1>
        <div class="form-group d-flex align-items-center mx-3">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success col-md-12 text-center submit-btn">
                    Submit
                </button>
            </form>
        </div>
    {% else %}
        <div class="form-group d-flex align-items-center mx-3">
            <P>You are not allowed to create posts, please, login!</P>
        </div>
    {% endif %}
{% endblock %}

blogapp/templates/blogapp/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="{% static 'scripts/jquery-3.5.1.min.js' %}"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.png' %}" sizes="96x96">
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'blog:home' %}">NGU&KG</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {#            <li class="nav-item active">#}
            {#                <a class="nav-link" href="{% url 'blog:home' %}">Home <span class="sr-only">(current)</span></a>#}
            {#            </li>#}
{#            <li class="nav-item active">#}
{#                <a class="nav-link" href="{% url 'blog:search' %}">#}
{#                    Category Search</a>#}
{#            </li>#}
            <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" id="dropdownMenu2" role="button"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                    {% for category in categories %}
                        <a class="dropdown-item" type="button"
                           href="/category/{{ category.name }}">{{ category|capfirst }}</a>
                    {% endfor %}
                </div>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts:favorite_list' %}">
                    Favorites posts</a>
            </li>

        {% if user.is_authenticated and user.is_superuser %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:createpost' %}">
                    Create Post</a>
            </li>
        {% endif %}
        </ul>

        <ul class="navbar-nav" style="margin-right: 150px;">
            <li class="nav-item active text-center">
                <a class="nav-link text-info font-weight-bold" href="{% url 'blog:home' %}">
                    {{ user.username|upper }}</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'blog:search' %}" method="get">
            <input class="form-control mr-sm-2"
                   type="search" placeholder="Search" name="q"
                   aria-label="Search" required>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>

        {% if user.is_authenticated %}
            <ul class="navbar-nav float-right">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profile</a>
                </li>
            </ul>
        {% else %}
            <ul class="navbar-nav float-right">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                </li>
            </ul>
        {% endif %}
    </div>
</nav>

{% block content %}
{% endblock %}

<script src="{% static 'scripts/popper.min.js' %}"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
</script>
<script src="{% static 'scripts/bootstrap.min.js' %}"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
</script>
</body>
</html>

blogapp/templates/blogapp/category.html
{% extends 'blogapp/base.html' %}
{% load static %}
{% block title %}Category list{% endblock %}

{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-12 pb-5">
                    <h1>List of {{ categorylist.category }} posts</h1>
                </div>
                {% if categorylist.posts %}
                    {% for post in categorylist.posts %}
                        <div class="col-md-4">
                            <a href="{% url 'blog:single_post' post.pk %}" class="text-dark">
                                <div class="card mb-4 box-shadow card-info">
                                    <img class="card-img-top" src="{{ post.image.url }}"
                                         style="width: 348px; height: 250px"
                                         alt="card img">
                                    <div class="card-body">
                                        <h2 style="font-size: 18px; font-weight: bold;">
                                            {{ post.title|truncatechars:10|capfirst }}
                                        </h2>
                                        <p class="card-text">{{ post.excerpt|truncatechars:10 }}</p>
                                        <div class="d-flex justify-content-between align-items-center">
                                            <small class="text-muted">{{ post.publish|date }}</small>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                {% else %}
                    <h4>No data to show!</h4>
                {% endif %}

            </div>
        </div>
    </div>
    {% include 'partials/footer.html' %}
{% endblock %}

blogapp/templates/blogapp/home.html
{% extends 'blogapp/base.html' %}
{% load static %}
{% block title %}Blog Home{% endblock %}


{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-12 pb-5">
                    <h1>List of posts</h1>
                </div>

                {% for post in posts %}
                    <div class="col-md-4">
                        <a href="{% url 'blog:single_post' post.pk %}" class="text-dark">
                            <div class="card mb-4 box-shadow card-info">
{#                                <img class="card-img-top" style="width: 350px; height: 250px" src="{{ post.image.url }}" alt="{{ post.title }}">#}
                                <div class="card-body">
                                    <h2 style="font-size: 20px; font-weight: bold;">
                                        {{ post.title|capfirst }}
                                    </h2>
                                    <p class="card-text">{{ post.excerpt|truncatechars:20 }}</p>
                                    <div class="d-flex justify-content-between date-post">
                                        <small class="text-muted">{{ post.publish|date }}</small>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>
    {% include 'partials/footer.html' %}
{% endblock %}

blogapp/templates/blogapp/search.html
{% extends 'blogapp/base.html' %}
{% load static %}
{% block title %}Blog Search{% endblock %}

{% block content %}

    <div class="mt-5 py-4">
        {% if q %}
            <div class="mx-5">
                <h5>You are searching for: "{{ q }}" </h5>
                <p>
                    {% with results.count as total_results %}
                        Found {{ total_results }} result{{ total_results|pluralize }}
                    {% endwith %}
                </p>
                <p>
                    <a href="{% url 'blog:search' %}" class="btn btn-primary mt-5"
                       role="button" aria-disabled="true">
                        New Search
                    </a>
                </p>
            </div>
        {% else %}
            <div class="my-5 mx-5">
                <form class="dropdown" method="get">
                    {% csrf_token %}
                    {{ form.q }}

                    <ul class="dropdown-menu col-12 pl-2" role="menu" aria-labelledby="menu" id="list">
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">HTML</a></li>
                        <div class="dropdown-divider"></div>
                        {#                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">CSS</a></li>#}
                        {#                        <div class="dropdown-divider"></div>#}
                        {#                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">JavaScript</a></li>#}
                    </ul>
                    {{ form.categories }}
                    <br>


                    <input class="btn btn-outline-success my-3" type="submit" value="Search"><br>
                </form>
            </div>
        {% endif %}
    </div>
    <div class="card-group">
        {% for post in results %}
            <div class="card border-dark mb-3 mx-5" style="max-width: 18rem;">
                <a href="{% url 'blog:single_post' post.pk %}">
                    <img class="rounded" src="{{ post.image.url }}" style="width: 304px; height: 250px">
                    <div class="card-header">
                        <a href="{% url 'blog:single_post' post.pk %}">{{ post.title }}</a>
                    </div>
                    <div class="card-body text-dark">
                        <p class="card-text">
                            {{ post.content|truncatechars:50 }}
                        </p>
                    </div>
                </a>
                <div class="card-footer bg-transparent border-info">Created on: {{ post.publish|date }}</div>
            </div>
        {% endfor %}
    </div>

    <script>
        $(document).on('keyup', '#id_q', function (e) {
            e.preventDefault();

            var results = [];
            // we will implement the search after the nbr of chars users typed
            var minlength = 3;

            if ($('#id_q').val().length >= minlength) {
                $.ajax({
                    type: 'POST',
                    {# send data that have gotten to our view #}
                    url: '{% url "blog:search" %}',
                    data: {
                        {# id_q its a search input q used to capture the value from users #}
                        ss: $('#id_q').val(),
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                        action: 'post'
                    },
                    success: function (json) {

                        $.each(JSON.parse(json.search_string), function (i, item) {
                            results.push('<li class="my-2 pl-2">' +
                                '<a href="/' + item.fields.slug + '">' +
                                item.fields.title + '</a></li>')
                        })

                        if (!$(".show")[0]) {
                            $('.menudd').trigger('click')
                        }

                        document.getElementById('list').innerHTML = (!results.length) ?
                            "No results match " : results.join('');
                    },
                    error: function (xhr, errmsg, err) {
                    },
                });
            }
        })
    </script>
{% endblock %}